esphome:
  name: sd-card

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart