esphome:
  name: sd-card

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart

esp32_camera_sd_card:
  id: esp_camera_sd_card

sensor:
  - platform: esp32_camera_sd_card
    type: USED_SPACE
    unit_of_measurement: Mb
    name: "SD card used space"
    filters:
      - lambda: return esp32_camera_sd_card::convertBytes(x, esp32_camera_sd_card::MemoryUnits::MegaByte);

  - platform: esp32_camera_sd_card
    type: TOTAL_SPACE
    name: "SD card total space"
    unit_of_measurement: Gb
    filters:
      - lambda: return esp32_camera_sd_card::convertBytes(x, esp32_camera_sd_card::MemoryUnits::GigaByte);